import sys
import os
import docx
import subprocess
import json
import re

# 转换视频播放秒数为ass文件要求的格式，获取片尾固定字幕的起始时间
def gettimestr(duration):
	secs = int(float(duration)) + 1
	secstr = ("0" + str(secs % 60))[-2:]
	minstr = ("0" + str(secs // 60))[-2:]

	secs1 = secs - 10
	secstr1 = ("0" + str(secs1 % 60))[-2:]
	minstr1 = ("0" + str(secs1 // 60))[-2:]
	return minstr1 + ":" + secstr1, minstr + ":" + secstr


dirname = "D:\\youzimu\\201803\\Honest Trailers - Thor_ Ragnarok"
# dirname = sys.argv[1]

# 保证路径以\结尾
if dirname[-1] != "\\":
	dirname = dirname + "\\"

# 遍历文件夹内文件
flist = os.listdir(dirname)
for efile in flist:
	assname = os.path.splitext(efile)[0]
	extname = os.path.splitext(efile)[1]
	# 获取doc文档内容
	if extname == ".doc" or extname == ".docx":
		print(efile)
		docpath = dirname+efile
		docfile = docx.Document(docpath)
		doctext = [paragraph.text for paragraph in docfile.paragraphs]

	# 获取视频文件相关信息
	if extname == ".mp4":
		print(efile)
		videopath = dirname+efile
		# 复制播放文件到temp.mp3,主要是为了防止因为文件名原因引起ffplay使用问题
		open("temp.mp4", "wb").write(open(videopath, "rb").read())	
		#运行ffprobe进程，将stdout解码为utf-8&转换为JSON 
		ffprobeOutput = subprocess.check_output("ffprobe -v quiet -print_format json -show_streams temp.mp4").decode("utf-8")
		ffprobeOutput = json.loads(ffprobeOutput)
		os.remove("temp.mp4")
		#查找高度和宽度
		videoheight = ffprobeOutput ['streams'] [0] ['height'] 
		videowidth = ffprobeOutput ['streams'] [0] ['width']
		duration = ffprobeOutput['streams'] [0] ['duration']
		print(videoheight,videowidth,duration)
		#print(ffprobeOutput)

# ass文件的头部信息
asshead = "[Script Info]\n" + \
	"; Script generated by Aegisub 3.2.2\n" + \
	"; http://www.aegisub.org/\n" + \
	"Title: Default Aegisub file\n" + \
	"ScriptType: v4.00+\n" + \
	"WrapStyle: 0\n" + \
	"ScaledBorderAndShadow: yes\n" + \
	"YCbCr Matrix: TV.601\n" + \
	"PlayResX: " + str(videowidth) + "\n" +\
	"PlayResY: " + str(videoheight)  + "\n"


asshead = asshead +	"[Aegisub Project Garbage]\n" + \
	"Audio File: " + videopath +"\n" + \
	"Video File: " + videopath +"\n" + \
	"Video AR Mode: 4\n" + \
	"Video AR Value: 1.777778\n" + \
	"Video Zoom Percent: 0.500000\n" + \
	"Scroll Position: 9\n" + \
	"Active Line: 15\n" + \
	"Video Position: 1208\n"

# ass文件的样式信息
assstyle = "[V4+ Styles]\n" + \
	"Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n" + \
	"Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1\n" + \
	"Style: 1080P柚子木中文,方正正粗黑_GBK,75,&H00D7E100,&HFFD7E100,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,4,2,15,15,15,1\n" + \
	"Style: 1080P柚子木注释,方正正准黑_GBK,70,&H0000FFFF,&HFF00FFFF,&HFF000000,&H00000000,-1,0,0,0,100,100,0,0,1,4,1,8,15,15,15,1\n" + \
	"Style: 720P柚子木中文,方正正粗黑_GBK,55,&H00D7E100,&HFFD7E100,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,3,2,10,10,10,1\n" + \
	"Style: 720P柚子木注释,方正正准黑_GBK,45,&H0000FFFF,&HFF00FFFF,&HFF000000,&H00000000,-1,0,0,0,100,100,0,0,1,3,1,8,10,10,10,1\n" + \
	"Style: 360P柚子木中文,方正正粗黑_GBK,25,&H00D7E100,&HFFD7E100,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,1.5,2,5,5,5,1\n" + \
	"Style: 360P柚子木注释,方正正准黑_GBK,23,&H0000FFFF,&HFF00FFFF,&HFF000000,&H00000000,-1,0,0,0,100,100,0,0,1,1.5,0.5,8,5,5,5,1\n" + \
	"Style: 480P柚子木中文,方正正粗黑_GBK,30,&H00D7E100,&HFFD7E100,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,2,2,5,5,7,1\n" + \
	"Style: 480P柚子木注释,方正正准黑_GBK,31,&H0000FFFF,&HFF00FFFF,&HFF000000,&H00000000,-1,0,0,0,100,100,0,0,1,1.7,0.25,8,5,5,7,1\n" + \
	"Style: 1080P-MV骚粉色妹子-英文,造字工房朗倩（非商用）常规体,75,&H008B12EA,&H008B12EA,&H00FFFFFF,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,4,0,2,10,10,10,1\n" + \
	"Style: 1080P-MV基佬蓝汉子-中文,造字工房朗倩（非商用）常规体,75,&H009CA702,&H00E6F014,&H00FFFFFF,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,4,0,2,10,10,10,1\n"


isnormal = 0  # 判断视频文件的分辨率是否是可以处理的分辨率

# 对不同的分辨率的视频定义 \N的替代内容、片头尾、所用样式
if videowidth == 1920 and videoheight == 1080:
	isnormal = 1
	linesplit = "\\N{\\fnCalibri\\fs50\\shad1.5\\bord3.5\\c&HFFFFFF&\\b0\\4c&H000000&\\3c&H000000&}"
	videohead = "Dialogue: 0,0:00:00.00,0:00:07.00,Default,,0,0,0,,{\\p1\\shad0\\blur0\\c&H000000&\\1a&H80&\\3a&H80&\\4a&H80&\\fad(0,500)\\pos(965,195)}m 0 0 l 0 0 l 0 0 l 2745 0 l 2745 777 l 0 777\n" + \
		"Dialogue: 0,0:00:00.00,0:00:07.00,Default,,0,0,0,,{\\c&HFFFFFF&\\shad0\\bord0\\fs65\\fn方正品尚黑简体\\b1\\fad(0,800)\\pos(965,186)}听译:{\\fs70\\c&HD7E100&}XXXX     {\\fs65\\c&HFFFFFF&}校正:{\\fs70\\c&HD7E100&}XXXX     {\\fs65\\c&HFFFFFF&}时轴:{\\fs70\\c&HD7E100&}XXXX\n" + \
		"Dialogue: 0,0:00:00.00,0:00:07.00,Default,,0,0,0,,{\\c&HFFFFFF&\\shad0\\bord0\\fs65\\fn方正品尚黑简体\\b1\\fad(0,800)\\pos(965,100.5)}微博搜索:{\\c&HD7E100&\\fs70}@柚子木字幕组   {\\c&HFFFFFF&\\fs65}微信号:{\\c&HD7E100&\\fs70}Youzimu\n"
	footstart, footend = gettimestr(duration)
	videofoot = "Dialogue: 0,0:"+footstart+".00,0:"+footend+".00,Default,,0,0,0,,{\\p1\\shad0\\blur0\\c&H000000&\\1a&H80&\\3a&H80&\\4a&H80&\\fad(500,0)\\pos(965,195)}m 0 0 l 0 0 l 0 0 l 2745 0 l 2745 777 l 0 777\n" + \
		"Dialogue: 0,0:"+footstart+".00,0:"+footend+".00,Default,,0,0,0,,{\\fsp1.5\\shad0\\bord0\\b100\\fs65\\fad(500,0)\\fn方正品尚黑简体\\c&HFFFFFF&\\pos(965,91.5)}柚子木字幕组招募听译、时间轴\n" + \
		"Dialogue: 0,0:"+footstart+".00,0:"+footend+".00,Default,,0,0,0,,{\\c&HFFFFFF&\\shad0\\bord0\\b100\\fs65\\fn方正品尚黑简体\\fad(500,0)\\pos(965,175.667)}欢迎登陆论坛{\\c&HD7E100&\\b900} www.youzimu.com\n"
	styleusing = "1080P柚子木中文"		

if videowidth == 1280 and videoheight == 720:
	isnormal = 1
	linesplit = "\\N{\\fnCalibri\\fs35\\shad1\\bord2.5\\c&HFFFFFF&\\b0\\4c&H000000&\\3c&H000000&}"
	videohead = "Dialogue: 0,0:00:00.00,0:00:07.00,Default,,0,0,0,,{\\p1\\shad0\\blur0\\c&H000000&\\1a&H80&\\3a&H80&\\4a&H80&\\fad(0,480)\\pos(640,130)}m 0 0 l 0 0 l 0 0 l 1830 0 l 1830 518 l 0 518\n" + \
		"Dialogue: 0,0:00:00.00,0:00:07.00,Default,,0,0,0,,{\\c&HFFFFFF&\\shad0\\bord0\\fs45\\fn方正品尚黑简体\\b1\\fad(0,800)\\pos(640,124)}听译:{\\fs48\\c&HD7E100&}XXXX     {\\fs45\\c&HFFFFFF&}校正:{\\fs48\\c&HD7E100&}XXXX     {\\fs45\\c&HFFFFFF&}时轴:{\\fs48\\c&HD7E100&}XXXX\n" + \
		"Dialogue: 0,0:00:00.00,0:00:07.00,Default,,0,0,0,,{\\c&HFFFFFF&\\shad0\\bord0\\fs45\\fn方正品尚黑简体\\b1\\fad(0,800)\\pos(640,67)}微博搜索:{\\c&HD7E100&\\fs48}@柚子木字幕组   {\\c&HFFFFFF&\\fs45}微信号:{\\c&HD7E100&\\fs48}Youzimu\n"
	footstart, footend = gettimestr(duration)
	videofoot = "Dialogue: 0,0:00:"+footstart+".00,0:"+footend+".00,Default,,0,0,0,,{\\p1\\shad0\\blur0\\c&H000000&\\1a&H80&\\3a&H80&\\4a&H80&\\fad(480,0)\\pos(640,130)}m 0 0 l 0 0 l 0 0 l 1830 0 l 1830 518 l 0 518\n" + \
		"Dialogue: 0,0:00:"+footstart+".00,0:"+footend+".00,Default,,0,0,0,,{\\fsp1\\shad0\\bord0\\b100\\fs45\\fad(480,0)\\fn方正品尚黑简体\\c&HFFFFFF&\\pos(640,61)}柚子木字幕组招募听译、时间轴\n" + \
		"Dialogue: 0,0:00:"+footstart+".00,0:"+footend+".00,Default,,0,0,0,,{\\c&HFFFFFF&\\shad0\\bord0\\b100\\fs45\\fn方正品尚黑简体\\fad(480,0)\\pos(640,126)}欢迎登陆论坛{\\c&HD7E100&\\b900} www.youzimu.com\n"
	styleusing = "720P柚子木中文"

if not isnormal:
	print("视频分辨率特殊")
	sys.exit()

# ass文件的事件部分
assevent = "[Events]\n" + \
	"Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"

assevent = assevent + videohead

# 将从doc文件中获取的内容合并起来，不再按段落分开
asstext = ""
for eachtext in doctext:
	asstext = asstext + eachtext + "\n"

# 确认格式符合要求
asstext, num = re.subn("([^\\x00-\\xff]) +(-)","\\1    \\2",asstext)
print(num)
asstext, num = re.subn("([^\\x00-\\xff]) +([^\\x00-\\xff])","\\1  \\2",asstext)
print(num)
asstext, num = re.subn("[“”]","\"",asstext)
print(num)

# 将内容分行， 替换\N
asslines = asstext.split("\n\n")
for eachline in asslines:
	assevent = assevent + "Dialogue: 0,0:00:00.00,0:00:00.00,"+styleusing+",,0,0,0,," + (eachline.replace("\n","\\N{\\fnCalibri\\fs50\\shad1.5\\bord3.5\\c&HFFFFFF&\\b0\\4c&H000000&\\3c&H000000&}")) + "\n"

assevent = assevent + videofoot

# 保存
open(dirname + assname + ".ass", "w", encoding = "gb18030").write(asshead + assstyle + assevent)
#print(asshead + assstyle + assevent)

